---
name: WriteCheck
main: kim\present\writecheck\WriteCheck
version: 1.3.3
api: [4.0.0]
author: PresentKim
website: https://github.com/PresentKim/WriteCheck-PMMP
description: Write a check for use it anywhere!
depend: [EconomyAPI]

permissions:
  wcheck.cmd:
    description: WriteCheck command
    default: true
...
