---
name: WriteCheck
main: kim\present\writecheck\WriteCheck
version: 1.3.4
api: [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 4.0.0]
author: PresentKim
description: Write a check for use it anywhere!
depend: [EconomyAPI]

permissions:
  wcheck.cmd:
    description: WriteCheck command
    default: true
...
