---
name:                   WriteCheck
main:                   kim\present\writecheck\WriteCheck
version:                1.1.3
api:                    [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author:                 PresentKim
website:                https://github.com/PresentKim/WriteCheck-PMMP

depend:                 [EconomyAPI]

permissions:
  wcheck.cmd:
    description:        WriteCheck command
    default:            true
    children:
      wcheck.cmd.write:
        description:    WriteCheck command - write
        default:        true
      wcheck.cmd.lang:
        description:    WriteCheck command - lang
        default:        op
      wcheck.cmd.reload:
        description:    WriteCheck command - reload
        default:        op
...
